# Importing all the necessary libraries

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout
from keras.utils import to_categorical
from PIL import Image
import os


C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (

# Seggregate the images into array along with their folders

In [2]:
Folders = []
Images  = []
total_sign = 43

path = os.getcwd()

for i in range(total_sign):
    subfoldr_path = os.path.join(path,'train',str(i))
    images        = os.listdir(subfoldr_path)
    
    for j in (images):
        try:
            image = Image.open(subfoldr_path+'\\'+j)
            image = image.resize((30,30))
            image = np.array(image)
            Images.append(image)
            Folders.append(i)
        except:
            print("Error loading image")
            



# Converting into array and printing the images and their folders in training set

In [3]:
Images = np.array(Images)
Folders = np.array(Folders)

In [4]:
print(Images)


[[[[ 75  78  80]
   [ 74  76  78]
   [ 85  86  84]
   ...
   [ 68  75  74]
   [ 65  69  68]
   [ 66  67  66]]

  [[ 83  84  86]
   [ 80  80  82]
   [ 88  88  83]
   ...
   [ 73  77  78]
   [ 76  78  75]
   [ 80  80  78]]

  [[ 78  78  80]
   [ 86  85  86]
   [ 90  89  90]
   ...
   [ 71  74  71]
   [ 73  74  69]
   [ 78  78  74]]

  ...

  [[133 134 139]
   [123 127 132]
   [112 121 125]
   ...
   [ 94  95  89]
   [ 97  98  91]
   [ 99 103  99]]

  [[ 91  95  99]
   [ 91  98 103]
   [ 75  86  90]
   ...
   [104 102  96]
   [110 113 104]
   [ 96 104  98]]

  [[ 85  84  87]
   [ 95 101 107]
   [ 63  76  81]
   ...
   [103 103  95]
   [ 99 102  90]
   [ 90  97  89]]]


 [[[ 69  73  73]
   [ 76  79  79]
   [ 75  77  77]
   ...
   [ 76  81  80]
   [ 71  77  77]
   [ 66  68  70]]

  [[ 65  69  69]
   [ 74  76  76]
   [ 84  84  83]
   ...
   [ 90  83  89]
   [ 74  79  84]
   [ 67  69  73]]

  [[ 63  68  68]
   [ 71  72  72]
   [ 81  79  77]
   ...
   [105  86  91]
   [ 71  75  76]
   [ 69  71

In [5]:
print(Folders)

[ 0  0  0 ... 42 42 42]


In [6]:
print(Images.shape)

(39209, 30, 30, 3)


# Splitting into training and testing dataset

In [14]:
X_train,X_test,Y_train,Y_test = train_test_split(Images,Folders,test_size=0.2,random_state=42)

# Converting the Folders which are outputs into one hot encoding

In [15]:
Y_train = to_categorical(Y_train,43)
Y_test  = to_categorical(Y_test,43)

# Building a model

In [16]:
model = Sequential()
model.add(Conv2D(filters=32,kernel_size=(5,5),activation='relu',input_shape=X_train.shape[1:]))

# Add a second convolutional layer

In [17]:
model.add(Conv2D(filters=32,kernel_size=(5,5),activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(rate=0.25))

#  Adding a third convolutional layer

In [18]:
model.add(Conv2D(filters=64,kernel_size=(3,3),activation='relu'))
model.add(Conv2D(filters=64,kernel_size=(3,3),activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.25))

# Flatening the model into a neural network consisting of input nodes anfd generate the output

In [19]:
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(rate=0.5))
model.add(Dense(43, activation='softmax'))

# Compiling of the model

In [20]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


In [22]:
epoch = 25

model.fit(X_train,Y_train,batch_size=32,epochs=epoch,validation_data=(X_test,Y_test))


Train on 31367 samples, validate on 7842 samples
Epoch 1/25
31367/31367 [==============================] - 157s 5ms/step - loss: 2.1052 - accuracy: 0.4688 - val_loss: 0.5975 - val_accuracy: 0.8388
Epoch 2/25
31367/31367 [==============================] - 152s 5ms/step - loss: 0.7245 - accuracy: 0.7877 - val_loss: 0.2487 - val_accuracy: 0.9320
Epoch 3/25
31367/31367 [==============================] - 153s 5ms/step - loss: 0.4727 - accuracy: 0.8616 - val_loss: 0.1196 - val_accuracy: 0.9637
Epoch 4/25
31367/31367 [==============================] - 153s 5ms/step - loss: 0.3402 - accuracy: 0.9027 - val_loss: 0.0995 - val_accuracy: 0.9735
Epoch 5/25
31367/31367 [==============================] - 153s 5ms/step - loss: 0.3196 - accuracy: 0.9107 - val_loss: 0.1085 - val_accuracy: 0.9702
Epoch 6/25
31367/31367 [==============================] - 153s 5ms/step - loss: 0.2741 - accuracy: 0.9251 - val_loss: 0.0653 - val_accuracy: 0.9858
Epoch 7/25
31367/31367 [==============================] - 154s

# Validation of model against a test data

In [26]:
from sklearn.metrics import accuracy_score
Y_test = pd.read_csv('Train.csv')

Folders   = Y_test['ClassId'].values
Images  = Y_test['Path'].values

data = []

for img in Images:
    image = Image.open(img)
    image = image.resize((30,30))
    data.append(np.array(image))

X_test = np.array(data)

pred = model.predict_classes(X_test)

accuracy_score(Folders,pred)

0.9857430691932975

# Save the model in classifier

In [27]:
model.save('traffic_classifier.h5')